language: java
jdk:
  - openjdk7
install:
  - python -h
  - apt-get install -y python2.7 python2.7-dev
  - python -h
before_script:
  - "export JAVA_OPTS=-Xmx512m"
env:
  - SPARK_VERSION=1.6
cache:
  directories:
  - $HOME/.m2
script:
  - mvn clean package -q -Dmaven.javadoc.skip=true
