sudo: required
language: java
jdk:
  - openjdk7
install:
  - hibench=$(pwd)
  - cd /opt/
  - wget http://d3kbcqa49mib13.cloudfront.net/spark-1.6.0-bin-hadoop2.6.tgz
  - tar -xzf spark-1.6.0-bin-hadoop2.6.tgz
  - wget http://mirror.nexcess.net/apache/hadoop/common/hadoop-2.6.5/hadoop-2.6.5.tar.gz
  - tar -xzf hadoop-2.6.5.tar.gz
  - cd ${hibench}
  - cp ./travis/spark-env.sh /opt/spark-1.6.0-bin-hadoop2.6/conf/
  - cp ./travis/core-site.xml /opt/hadoop-2.6.5/etc/hadoop/
  - cp ./travis/hdfs-site.xml /opt/hadoop-2.6.5/etc/hadoop/
  - cp ./travis/mapred-site.xml /opt/hadoop-2.6.5/etc/hadoop/
  - cp ./travis/yarn-site.xml /opt/hadoop-2.6.5/etc/hadoop/
#  - cp ./travis/hadoop-env.sh /opt/hadoop-2.6.5/etc/hadoop/
#  - cp ./travis/hibench.conf ./conf/
before_script:
  - "export JAVA_OPTS=-Xmx512m"
env:
  - SPARK_VERSION=1.6
cache:
  directories:
  - $HOME/.m2
script:
  - mvn clean package -q -Dmaven.javadoc.skip=true
  - sudo ./travis/configssh.sh
  - sudo ./travis/restart-hadoop-spark.sh
  - cp ./travis/hadoop.conf ./conf/
  - cp ./travis/spark.conf ./conf/
  - sudo ./bin/workloads/micro/wordcount/prepare/prepare.sh
