sudo: required
language: java
jdk:
  - openjdk7
install:
  - hibench=$(pwd)
  - cd /opt/
  - wget http://d3kbcqa49mib13.cloudfront.net/spark-1.6.0-bin-hadoop2.6.tgz
  - tar -xzf spark-1.6.0-bin-hadoop2.6.tgz
  - wget http://mirror.nexcess.net/apache/hadoop/common/hadoop-2.6.5/hadoop-2.6.5.tar.gz
  - tar -xzf hadoop-2.6.5.tar.gz
  - cd ${hibench}
  - cp ./travis/spark-env.sh /opt/spark-1.6.0-bin-hadoop2.6/conf/
  - cp ./travis/core-site.xml /opt/hadoop-2.6.5/etc/hadoop/
  - cp ./travis/hdfs-site.xml /opt/hadoop-2.6.5/etc/hadoop/
  - cp ./travis/mapred-site.xml /opt/hadoop-2.6.5/etc/hadoop/
  - cp ./travis/yarn-site.xml /opt/hadoop-2.6.5/etc/hadoop/
before_script:
  - "export JAVA_OPTS=-Xmx512m"
  - "export HADOOP_HOME=/opt/hadoop-2.6.5"
  - "export SPARK_HOME=/opt/spark-1.6.0-bin-hadoop2.6"
env:
  - SPARK_VERSION=1.6
cache:
  directories:
  - $HOME/.m2
script:
#  - mvn clean package -q -Dmaven.javadoc.skip=true
  - ssh-keygen -q -N "" -t rsa -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - sudo ssh  -o StrictHostKeyChecking=no  127.0.0.1
  - sudo ./travis/restart-hadoop-spark.sh
